### PR TITLE
fix(validation): requires all top-level type definitions to have a name

### LINKED ISSUE #139: Require all top-level type definitions to have a name
As noted in #138, this library does not require top-level type definitions within a schema to have a name, and such types have an "implicit name" assigned by calling `toString()` on the type definition's in-memory representation (as an IonValue).  Allowing callers to retrieve an unnamed type by its "implicit name" is brittle at best, and is considered a mis-feature.

This library should:
1. require all top-level type definitions to have a name
1. not allow any type definitions to be retrieved by an "implicit name"

### PR DESCRIPTION
**Pull request by pbcornell**
*Description of changes:*
* requires all top-level type definitions to have a name (otherwise there's no good way to refer to them)
* I mistakenly pushed https://github.com/amzn/ion-schema-tests/commit/9937507ee8f11949e6f0489bee6f54b83c3f157f without a review; please comment on that as well
* the majority of test files in ion-schema-tests contain type definitions that don't have a name. these proposed changes include logic in ISLforISLTestRunner.kt to provide a type name, if absent; this allows all the ion-schema-tests test cases to pass without needing to provide a name for each type
* for backwards compatibility, if needed, provides an option to not throw on types that don't have a name

Resolves #139 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/com/amazon/ionschema/IonSchemaSystemBuilder.kt [hunk 1]
```diff
@@ -81,6 +82,21 @@ class IonSchemaSystemBuilder private constructor() {
...
+     * Allows top-level types to not have a name.  Such types can't be referred to
+     * by name and are thereby of limited (if any?) value.  This option if provided
+     * in case consumers have defined top-level types that don't have names.
+     * Should only be used if needed for backwards compatibility with v1.0; this will
+     * be removed in a future release.
+     *
+     * @since 1.1
+     */
+    @Deprecated("For backwards compatibility with v1.0")
+    fun allowUnnamedTopLevelTypes(): IonSchemaSystemBuilder {
```
Comment (therapon) [inline src/com/amazon/ionschema/IonSchemaSystemBuilder.kt:95]: nit: unnamed = anonymous, rename to `allowAnonymousTopLevelTypes()`

Comment (pbcornell) [reply src/com/amazon/ionschema/IonSchemaSystemBuilder.kt]: agreed, adds clarity, changed, thank you
